// src/components/clinica/Formularios/plantillas.js

export const TIPOS_FORMULARIO = {
  general: {
    nombre: 'General',
    descripcion: 'Formulario estándar para evaluación inicial',
    preguntas: [],
  },
  algias: {
    nombre: 'Algias (Dolor Musculoesquelético)',
    descripcion: 'Enfocado en dolor general, localización e irradiación',
    preguntas: [
      { label: '¿El dolor se irradia a otra zona?', tipo: 'text', placeholder: 'Ej: al brazo, a la pierna...' },
      { label: '¿Hay algún movimiento que lo desencadene?', tipo: 'text', placeholder: 'Ej: al levantar el brazo, al girar...' },
      { label: '¿El dolor le impide realizar alguna actividad?', tipo: 'textarea', placeholder: 'Describe las limitaciones' },
      { label: '¿El dolor es continuo o intermitente?', tipo: 'select', opciones: ['Continuo', 'Intermitente'] },
      { label: '¿El dolor aparece en reposo o solo al moverse?', tipo: 'select', opciones: ['Solo al moverse', 'En reposo', 'Ambos'] },
      { label: '¿Ha probado algún tratamiento previo?', tipo: 'text', placeholder: 'Ej: medicamentos, fisioterapia' },
      { label: '¿El dolor afecta su sueño?', tipo: 'select', opciones: ['Sí', 'No', 'A veces'] },
      { label: '¿Tiene antecedentes de dolor similar?', tipo: 'text', placeholder: 'Describa si ha tenido episodios anteriores' },
      { label: '¿El dolor se acompaña de otros síntomas (fiebre, malestar general)?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Qué tipo de actividades realiza en su día a día que podrían estar relacionadas?', tipo: 'textarea', placeholder: 'Describa su rutina' },
    ],
  },
  deportivo: {
    nombre: 'Deportivo / Lesiones de esfuerzo',
    descripcion: 'Para lesiones relacionadas con actividad física o deporte',
    preguntas: [
      { label: '¿Qué deporte practica?', tipo: 'text', placeholder: 'Ej: fútbol, running, natación...' },
      { label: 'Frecuencia e intensidad del entrenamiento', tipo: 'text', placeholder: 'Ej: 3 veces por semana, alta intensidad' },
      { label: '¿El dolor aparece durante o después del ejercicio?', tipo: 'select', opciones: ['Durante', 'Después', 'Ambos'] },
      { label: '¿Ha tenido lesiones previas en la misma zona?', tipo: 'text', placeholder: 'Ej: esguince de tobillo hace 1 año' },
      { label: '¿Realiza calentamiento y estiramientos antes de entrenar?', tipo: 'select', opciones: ['Sí', 'No', 'A veces'] },
      { label: '¿El dolor le impide entrenar al 100%?', tipo: 'select', opciones: ['Sí', 'No', 'Parcialmente'] },
      { label: '¿Ha consultado con un entrenador o preparador físico?', tipo: 'text', placeholder: 'Detalle si ha recibido asesoría' },
      { label: '¿Utiliza equipo de protección o soportes?', tipo: 'text', placeholder: 'Ej: muñequeras, rodilleras, cintas' },
      { label: '¿El dolor empeora con la carga o el impacto?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Ha hecho cambios recientes en su técnica deportiva?', tipo: 'text', placeholder: 'Describa los cambios' },
    ],
  },
  geriatrico: {
    nombre: 'Geriatría / Adulto Mayor',
    descripcion: 'Enfocado en caídas, fragilidad, osteoporosis, artrosis',
    preguntas: [
      { label: '¿Ha sufrido caídas en los últimos 6 meses?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Tiene dificultad para subir escaleras?', tipo: 'select', opciones: ['Ninguna', 'Leve', 'Moderada', 'Severa'] },
      { label: '¿Utiliza algún apoyo para caminar?', tipo: 'text', placeholder: 'Ej: bastón, andador' },
      { label: '¿Tiene osteoporosis o antecedentes de fracturas?', tipo: 'text', placeholder: 'Detalle si tiene diagnóstico' },
      { label: '¿Tiene artrosis en alguna articulación?', tipo: 'text', placeholder: 'Ej: rodillas, caderas, manos' },
      { label: '¿Ha tenido mareos o vértigo al levantarse?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Tiene problemas de visión o audición que puedan afectar su equilibrio?', tipo: 'text', placeholder: 'Describa' },
      { label: '¿Realiza algún tipo de ejercicio regular (caminatas, gimnasia)?', tipo: 'text', placeholder: 'Detalle la frecuencia' },
      { label: '¿Ha notado pérdida de memoria o confusión reciente?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Tiene incontinencia urinaria?', tipo: 'select', opciones: ['Sí', 'No', 'Ocasional'] },
    ],
  },
  neurologico: {
    nombre: 'Neurológico / Alteraciones del SNC',
    descripcion: 'Para evaluar reflejos, sensibilidad, fuerza, mareos',
    preguntas: [
      { label: '¿Tiene mareos o vértigo?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Ha notado pérdida de fuerza en alguna extremidad?', tipo: 'text', placeholder: 'Ej: brazo izquierdo' },
      { label: '¿Tiene alteraciones de la sensibilidad (hormigueo, entumecimiento)?', tipo: 'text', placeholder: 'Describe la zona' },
      { label: '¿Ha sufrido algún accidente vascular cerebral (ictus)?', tipo: 'text', placeholder: 'Fecha y secuelas' },
      { label: '¿Tiene temblores o movimientos involuntarios?', tipo: 'text', placeholder: 'Describa' },
      { label: '¿Ha perdido el conocimiento alguna vez?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Tiene dificultad para hablar o tragar?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Le han diagnosticado alguna enfermedad neurológica (Parkinson, esclerosis múltiple)?', tipo: 'text', placeholder: 'Detalle' },
      { label: '¿Tiene problemas de equilibrio al caminar?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Ha tenido convulsiones o episodios de confusión?', tipo: 'text', placeholder: 'Describa' },
    ],
  },
  oncologico: {
    nombre: 'Oncológico / Paciente con cáncer',
    descripcion: 'Enfocado en dolor oncológico, fatiga, tratamientos recibidos',
    preguntas: [
      { label: 'Tipo de cáncer diagnosticado', tipo: 'text', placeholder: 'Ej: mama, próstata, pulmón' },
      { label: 'Fecha de diagnóstico y etapa (si la conoce)', tipo: 'text', placeholder: 'Ej: 2024, estadio II' },
      { label: 'Tratamientos recibidos (cirugía, quimioterapia, radioterapia)', tipo: 'textarea', placeholder: 'Describa los tratamientos' },
      { label: '¿Tiene dolor oncológico? (EVA)', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Ha sufrido fracturas patológicas?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Tiene neuropatía periférica (hormigueo, quemazón)?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: 'Fatiga general (escala 1-10)', tipo: 'number', placeholder: '0 (sin fatiga) a 10 (máxima)' },
      { label: '¿Tiene problemas de movilidad o debilidad muscular?', tipo: 'text', placeholder: 'Describa' },
      { label: '¿Ha hecho rehabilitación oncológica previamente?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Qué expectativas tiene con la terapia?', tipo: 'textarea', placeholder: 'Comparta sus objetivos' },
    ],
  },
  pediatrico: {
    nombre: 'Pediátrico / Niños y adolescentes',
    descripcion: 'Adaptado para evaluar problemas musculoesqueléticos en menores',
    preguntas: [
      { label: 'Edad del niño/a', tipo: 'number', placeholder: 'Ej: 6' },
      { label: '¿Cuál es el motivo de la consulta?', tipo: 'text', placeholder: 'Describa el problema' },
      { label: '¿Ha tenido fiebre, infecciones o enfermedades recientes?', tipo: 'text', placeholder: 'Detalle' },
      { label: '¿Presenta cojera o dificultad para caminar?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Tiene dolor en las articulaciones o músculos?', tipo: 'text', placeholder: 'Describa la zona' },
      { label: '¿Ha tenido lesiones deportivas?', tipo: 'text', placeholder: 'Detalle el tipo de deporte y lesión' },
      { label: '¿Tiene antecedentes de enfermedades reumáticas o autoinmunes?', tipo: 'text', placeholder: 'Ej: artritis juvenil' },
      { label: '¿El niño/a muestra signos de fatiga o debilidad?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Ha notado cambios en su crecimiento o desarrollo?', tipo: 'text', placeholder: 'Describa' },
      { label: '¿Cómo afecta el problema a su actividad diaria (colegio, juegos)?', tipo: 'textarea', placeholder: 'Describa' },
    ],
  },
  reumatologico: {
    nombre: 'Reumatológico / Enfermedades autoinmunes',
    descripcion: 'Enfocado en artritis, lupus, esclerodermia, etc.',
    preguntas: [
      { label: 'Diagnóstico reumatológico (ej. artritis reumatoide, lupus, etc.)', tipo: 'text', placeholder: 'Detalle el diagnóstico' },
      { label: 'Tiempo de evolución desde el diagnóstico', tipo: 'text', placeholder: 'Ej: 5 años' },
      { label: '¿Tiene rigidez matutina? ¿Cuánto dura?', tipo: 'text', placeholder: 'Ej: 30 minutos' },
      { label: '¿Qué articulaciones están afectadas?', tipo: 'text', placeholder: 'Ej: manos, muñecas, rodillas' },
      { label: '¿Ha tenido brotes inflamatorios recientes?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: 'Medicamentos que toma (biológicos, corticosteroides, etc.)', tipo: 'textarea', placeholder: 'Lista de medicamentos' },
      { label: '¿Tiene fatiga crónica? (escala 1-10)', tipo: 'number', placeholder: '0-10' },
      { label: '¿Ha tenido osteoporosis o fracturas por esteroides?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Realiza ejercicio regular? ¿Cuál?', tipo: 'text', placeholder: 'Describa' },
      { label: '¿Cómo afecta la enfermedad a su vida diaria?', tipo: 'textarea', placeholder: 'Describa las limitaciones' },
    ],
  },
  vestibular: {
    nombre: 'Vestibular / Equilibrio y mareos',
    descripcion: 'Para evaluar problemas de equilibrio, vértigo y caídas',
    preguntas: [
      { label: '¿Tiene episodios de vértigo o mareo?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Cuándo aparecen? (al girar la cabeza, al levantarse, etc.)', tipo: 'text', placeholder: 'Describa el desencadenante' },
      { label: '¿Ha tenido caídas en los últimos 6 meses?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Siente inestabilidad al caminar?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Tiene problemas de audición o acúfenos?', tipo: 'text', placeholder: 'Describa' },
      { label: '¿Ha sido diagnosticado con vértigo posicional, enfermedad de Menière, etc.?', tipo: 'text', placeholder: 'Detalle el diagnóstico' },
      { label: '¿El vértigo le impide realizar actividades diarias?', tipo: 'select', opciones: ['Sí', 'No', 'A veces'] },
      { label: '¿Tiene nistagmo (movimiento involuntario de los ojos)?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Ha realizado pruebas vestibulares?', tipo: 'text', placeholder: 'Describa las pruebas' },
      { label: '¿Ha hecho rehabilitación vestibular anteriormente?', tipo: 'select', opciones: ['Sí', 'No'] },
    ],
  },
  postquirurgico: {
    nombre: 'Post-Quirúrgico / Rehabilitación',
    descripcion: 'Para pacientes que han sido operados recientemente',
    preguntas: [
      { label: 'Tipo de cirugía realizada', tipo: 'text', placeholder: 'Ej: artroscopia de rodilla, prótesis de cadera' },
      { label: 'Fecha de la cirugía', tipo: 'text', placeholder: 'Ej: hace 2 semanas' },
      { label: '¿Cuál es el objetivo principal de la rehabilitación?', tipo: 'text', placeholder: 'Ej: recuperar movilidad, reducir dolor' },
      { label: '¿Tiene dolor en la zona operada? (EVA)', tipo: 'number', placeholder: '0-10' },
      { label: '¿Tiene limitación del rango de movimiento?', tipo: 'text', placeholder: 'Describa qué movimientos no puede hacer' },
      { label: '¿Usa ayudas técnicas (muletas, andador)?', tipo: 'text', placeholder: 'Detalle' },
      { label: '¿Ha hecho rehabilitación antes?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Presenta inflamación o enrojecimiento en la zona?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Ha tenido fiebre o signos de infección?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Cuáles son sus expectativas de recuperación?', tipo: 'textarea', placeholder: 'Describa' },
    ],
  },
  dolor_cronico: {
    nombre: 'Dolor Crónico',
    descripcion: 'Para pacientes con dolor persistente (>3 meses)',
    preguntas: [
      { label: 'Tiempo de evolución del dolor (meses/años)', tipo: 'text', placeholder: 'Ej: 2 años' },
      { label: 'Ubicación del dolor (puede ser múltiple)', tipo: 'text', placeholder: 'Describa las zonas' },
      { label: 'Intensidad promedio (EVA)', tipo: 'number', placeholder: '0-10' },
      { label: '¿El dolor es constante o fluctuante?', tipo: 'select', opciones: ['Constante', 'Fluctuante'] },
      { label: 'Tratamientos previos (farmacológicos, fisioterapia, etc.)', tipo: 'textarea', placeholder: 'Detalle los tratamientos' },
      { label: '¿Tiene ansiedad o depresión asociada?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿El dolor afecta su sueño y estado de ánimo?', tipo: 'select', opciones: ['Sí', 'No', 'Mucho'] },
      { label: '¿Ha recibido terapia psicológica o de manejo del dolor?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Qué factores empeoran o mejoran el dolor?', tipo: 'text', placeholder: 'Describa' },
      { label: 'Objetivos de la rehabilitación', tipo: 'textarea', placeholder: '¿Qué espera lograr?' },
    ],
  },
  laboral: {
    nombre: 'Laboral / Ergonomía',
    descripcion: 'Enfocado en lesiones relacionadas con el trabajo y posturas forzadas',
    preguntas: [
      { label: 'Ocupación actual', tipo: 'text', placeholder: 'Ej: oficinista, carpintero, conductor' },
      { label: 'Tiempo en la ocupación actual', tipo: 'text', placeholder: 'Ej: 5 años' },
      { label: 'Posturas más frecuentes en el trabajo', tipo: 'text', placeholder: 'Ej: sentado prolongado, de pie, posturas forzadas' },
      { label: '¿Realiza movimientos repetitivos?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Levanta pesos de forma habitual?', tipo: 'text', placeholder: 'Ej: más de 10 kg' },
      { label: '¿Utiliza herramientas que vibren?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Ha tenido accidentes laborales?', tipo: 'text', placeholder: 'Describa' },
      { label: '¿El dolor empeora durante la jornada laboral?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Tiene pausas activas o ejercicios en el trabajo?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Cómo afecta el problema a su rendimiento laboral?', tipo: 'textarea', placeholder: 'Describa' },
    ],
  },
  psicosocial: {
    nombre: 'Psicosocial / Factores emocionales y sociales',
    descripcion: 'Para evaluar el impacto emocional y social del problema de salud',
    preguntas: [
      { label: '¿Cómo describiría su estado de ánimo general?', tipo: 'text', placeholder: 'Ej: ansioso, deprimido, estable' },
      { label: '¿El problema de salud le impide realizar actividades que antes disfrutaba?', tipo: 'select', opciones: ['Sí', 'No', 'Parcialmente'] },
      { label: '¿Tiene apoyo familiar o social?', tipo: 'select', opciones: ['Sí', 'No', 'Limitado'] },
      { label: '¿Ha tenido cambios en el apetito o el sueño debido al dolor?', tipo: 'text', placeholder: 'Describa' },
      { label: '¿Siente que el dolor controla su vida?', tipo: 'select', opciones: ['Sí', 'No', 'A veces'] },
      { label: '¿Ha recibido orientación psicológica?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Tiene pensamientos negativos recurrentes sobre su salud?', tipo: 'select', opciones: ['Sí', 'No'] },
      { label: '¿Cómo maneja el estrés en su día a día?', tipo: 'text', placeholder: 'Describa sus estrategias' },
      { label: '¿El problema afecta su vida laboral o económica?', tipo: 'text', placeholder: 'Describa' },
      { label: '¿Qué espera conseguir con la terapia?', tipo: 'textarea', placeholder: 'Describa sus metas' },
    ],
  },
};